// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5YcdpdhIiH-A4_gkSAfCIYudOYh3XwuY',
    appId: '1:46044446240:web:cac50d790a6f6e56e98645',
    messagingSenderId: '46044446240',
    projectId: 'jeepez-5c65d',
    authDomain: 'jeepez-5c65d.firebaseapp.com',
    storageBucket: 'jeepez-5c65d.firebasestorage.app',
    measurementId: 'G-XQQN99XC04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSmxv2rQ2nnSOIXMnjHm0kDWYECShj7jg',
    appId: '1:46044446240:android:6b99e176bcba8217e98645',
    messagingSenderId: '46044446240',
    projectId: 'jeepez-5c65d',
    storageBucket: 'jeepez-5c65d.firebasestorage.app',
  );
}
